### ISSUE TITLE
Storage permission issue

### ISSUE THREAD

**Issue by Sohil876** [siddastic/jside#1]
![Screenshot_20220419-164609](https://user-images.githubusercontent.com/3389469/163992125-00b381e1-6a1c-4924-9afd-4697516e957a.png)

No matter what i do this just keeps popping up when i try to browse files or open a folder, when i press grant the popup just reappears and nothing happens and it does not ask me for permission.
Ive tried reinstalling, clearing data of app, give app storage permission manually, its still same, im on oneui2 android10.

**Comment by siddastic** [comment]
I'll test it on an android 10 emulator, it might be because of new All Files Access Permission

**Comment by siddastic** [comment]
just posted new update, it should be resolved

**Comment by Sohil876** [comment]
Yeah fixed, thnx.
